language: node_js
node_js: lts/*

# Travis-CI Caching
cache: npm

branches:
  only:
    - master

# S: Build Lifecycle
install:
  - npm install

script:
  - npm run build -- --configuration production
  - cp dist/laputa/index.html dist/laputa/404.html

# E: Build LifeCycle


# GitHub Pages Deployment
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
  local-dir: dist/laputa
